# Generated by Django 3.1.3 on 2020-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('crystals', models.PositiveIntegerField(db_index=True, default=0)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('userpic', models.CharField(blank=True, max_length=128)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
    ]
