# Generated by Django 3.1.3 on 2020-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locale',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
