# Generated by Django 3.1.3 on 2020-11-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_account_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
