# Generated by Django 3.1.3 on 2020-11-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
