# Generated by Django 3.1.3 on 2020-12-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20201120_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_last_interaction',
            field=models.DateTimeField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='handled_profile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='invite_code',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
