# Generated by Django 3.1.3 on 2020-12-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('day', models.DateField(blank=True, db_index=True, null=True)),
                ('month', models.DateField(blank=True, db_index=True, null=True)),
                ('crystals', models.IntegerField()),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'Redeem Rewards'), (1, 'Level completed'), (2, 'User registered'), (3, 'Survey'), (4, 'Offer Fyber'), (5, 'Offer Pollfish'), (6, 'Offer TapJoy'), (7, 'Rewarded Video'), (8, 'Offer IronSrc'), (9, 'Game First Install'), (10, 'Raffle ticket')], db_index=True)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('level', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
            ],
        ),
        migrations.CreateModel(
            name='LevelCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(db_index=True, null=True)),
                ('uid', models.CharField(db_index=True, max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
            ],
            options={
                'unique_together': {('uid', 'account')},
            },
        ),
    ]
