# Generated by Django 3.1.3 on 2020-12-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_levelcompletion_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost', models.PositiveIntegerField()),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('end_tickets_sale', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Finished')], db_index=True)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaffleParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(default=False)),
                ('was_checked', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='db.raffle')),
            ],
            options={
                'unique_together': {('account', 'raffle')},
            },
        ),
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_time', models.DateTimeField(db_index=True)),
                ('number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('raffle_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='db.raffleparticipation')),
            ],
        ),
        migrations.AddField(
            model_name='raffle',
            name='participants',
            field=models.ManyToManyField(related_name='raffles', through='db.RaffleParticipation', to='db.Account'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.account'),
        ),
    ]
