# Generated by Django 3.1.3 on 2020-12-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20201216_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='raffle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.raffle'),
        ),
    ]
