# Generated by Django 3.1.3 on 2020-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_raffle_winner_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='winner_ticket',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
