# Generated by Django 3.1.3 on 2020-12-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20201217_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='winner_ticket',
        ),
    ]
