# Generated by Django 3.1.3 on 2020-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_raffle_winner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='source_game',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
