# Generated by Django 3.1.3 on 2021-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20201218_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollfishUniqueTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=48, unique=True)),
            ],
        ),
    ]
