# Generated by Django 3.1.3 on 2021-01-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_pollfishuniquetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='career',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADVERTISING'), (2, 'agriculture forestry fishing or hunting'), (3, 'arts entertainment or recreation'), (4, 'AUTOMOTIVE'), (5, 'broadcasting'), (6, 'construction'), (7, 'consulting'), (8, 'education'), (9, 'fashion apparel'), (10, 'finance and insurance'), (11, 'government and public administration'), (12, 'health care and social assistance'), (13, 'homemaker'), (14, 'hotel and food services'), (15, 'human resources'), (16, 'information other'), (17, 'information services and data'), (18, 'legal services'), (19, 'manufacturing computer and electronics'), (20, 'manufacturing other'), (21, 'market research'), (22, 'marketing sales'), (23, 'military'), (24, 'mining'), (25, 'personal services'), (26, 'processing'), (27, 'publishing'), (28, 'real estate rental or leasing'), (29, 'religious'), (30, 'retail'), (31, 'scientific or technical services'), (32, 'security'), (33, 'shipping distribution'), (34, 'software'), (35, 'student'), (36, 'telecommunications'), (37, 'transportation and warehousing'), (38, 'unemployed'), (39, 'energy utilities oil and gas'), (40, 'wholesale'), (41, 'other')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'elementary school'), (2, 'middle school'), (3, 'high school'), (4, 'vocational technical college'), (5, 'university'), (6, 'post graduate'), (7, 'prefer not to say+')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='employment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'self emplyed'), (2, 'unemployed (looking for)'), (3, 'unemployed (not looking for)'), (4, 'homemaker'), (5, 'student'), (6, 'military'), (7, 'retired'), (8, 'unable to work'), (9, 'other')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (3, 'other')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'lower 1'), (2, 'lower 2'), (3, 'middle 1'), (4, 'middle 2'), (5, 'high 1'), (6, 'high 2'), (7, 'high 3'), (8, 'prefer not to say')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='kids',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6+'), (8, 'prefer not to say')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='marital_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'single'), (2, 'married'), (3, 'divorced'), (4, 'living with partner'), (5, 'widow'), (6, 'prefer not to say')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='race',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'arab'), (2, 'asian'), (3, 'black'), (4, 'white'), (5, 'hispanic'), (6, 'latino'), (7, 'multiracial'), (8, 'other'), (9, 'prefer not to say')], null=True),
        ),
    ]
