# Generated by Django 3.1.3 on 2021-01-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20210122_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='career',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'agriculture forestry fishing or hunting'), (1, 'arts entertainment or recreation'), (2, 'broadcasting'), (3, 'construction'), (4, 'education'), (5, 'finance and insurance'), (6, 'government and public administration'), (7, 'health care and social assistance'), (8, 'homemaker'), (9, 'hotel and food services'), (10, 'information other'), (11, 'information services and data'), (12, 'legal services'), (13, 'manufacturing computer and electronics'), (14, 'manufacturing other'), (15, 'military'), (16, 'mining'), (17, 'processing'), (18, 'publishing'), (19, 'real estate rental or leasing'), (20, 'religious'), (21, 'retail'), (22, 'retired'), (23, 'scientific or technical services'), (24, 'software'), (25, 'student'), (26, 'telecommunications'), (27, 'transportation and warehousing'), (28, 'unemployed'), (29, 'energy utilities oil and gas'), (30, 'wholesale'), (31, 'other'), (32, 'advertising'), (33, 'automotive'), (34, 'consulting'), (35, 'fashion apparel'), (36, 'human resources'), (37, 'market research'), (38, 'marketing sales'), (39, 'shipping distribution'), (40, 'personal services'), (41, 'security')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'elementary school'), (1, 'middle school'), (2, 'high school'), (3, 'vocational technical college'), (4, 'university'), (5, 'post graduate')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='employment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'EMPLOYED_FOR_WAGES'), (1, 'self emplyed'), (2, 'unemployed (looking for)'), (3, 'unemployed (not looking for)'), (4, 'homemaker'), (5, 'student'), (6, 'military'), (7, 'retired'), (8, 'unable to work'), (9, 'other')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'male'), (1, 'female'), (3, 'other')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'lower 1'), (1, 'lower 2'), (2, 'middle 1'), (3, 'middle 2'), (4, 'high 1'), (5, 'high 2'), (6, 'high 3'), (7, 'prefer not to say')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='kids',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6+'), (7, 'prefer not to say')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='marital_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'single'), (1, 'married'), (2, 'divorced'), (3, 'living with partner'), (4, 'separated'), (5, 'widow'), (6, 'prefer not to say')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='race',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'arab'), (1, 'asian'), (2, 'black'), (3, 'white'), (4, 'hispanic'), (5, 'latino'), (6, 'multiracial'), (7, 'other'), (8, 'prefer not to say')], null=True),
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.PositiveIntegerField(choices=[(1, 'Leaderboard position'), (2, 'Raffle')], db_index=True)),
                ('amount_crystals', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Info needed'), (2, 'Processing'), (3, 'Paid')], db_index=True)),
                ('user_details', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
            ],
        ),
    ]
