# Generated by Django 3.1.3 on 2021-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20210126_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='amount_crystals',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
