# Generated by Django 3.1.3 on 2021-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20210126_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='amount_crystals',
        ),
        migrations.AlterField(
            model_name='rewards',
            name='amount',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
