# Generated by Django 3.1.3 on 2021-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20210127_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
