# Generated by Django 3.1.3 on 2021-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_account_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
