# Generated by Django 3.1.3 on 2021-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20210616_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ft_wallet',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
