# Generated by Django 3.1.3 on 2021-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_account_ft_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_surf_linked',
            field=models.BooleanField(default=False),
        ),
    ]
