# Generated by Django 3.1.3 on 2021-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_account_is_surf_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='crystals',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Crystals(delta)'),
        ),
    ]
