# Generated by Django 3.1.3 on 2021-08-03 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20210803_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
