# Generated by Django 3.1.3 on 2021-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_raffle_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='prize',
            field=models.FloatField(),
        ),
    ]
