# Generated by Django 3.1.3 on 2021-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20210803_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='amount',
            field=models.FloatField(),
        ),
    ]
