# Generated by Django 3.1.3 on 2021-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_auto_20210806_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='rate',
            field=models.FloatField(default=0.33),
            preserve_default=False,
        ),
    ]
