# Generated by Django 3.2.6 on 2021-08-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_rewards_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Redeem Rewards'), (1, 'Level completed'), (2, 'User registered'), (3, 'Survey'), (4, 'Offer Fyber'), (5, 'Offer Pollfish'), (6, 'Offer TapJoy'), (7, 'Rewarded Video'), (8, 'Offer IronSrc'), (9, 'Game First Install'), (10, 'Raffle ticket'), (11, 'Least from delta wirhdraw')], db_index=True),
        ),
    ]
